parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
env:
  browser: true
  node: true
  es6: true
plugins:
  - prettier
  - flowtype
  - import
  - react
extends:
  - plugin:react/recommended
  - plugin:flowtype/recommended
  - plugin:import/errors
  - prettier
  - prettier/flowtype
  - prettier/react
rules:
  # prettier
  prettier/prettier:
    - 2
    -
      trailingComma: none
      singleQuote: false
      semi: false
  # rules
  prefer-const: 2
  no-unused-vars:
    - 2
    - argsIgnorePattern: ^_
  no-multiple-empty-lines:
    - 2
    - max: 1
  # react
  react/prefer-stateless-function: 2
  # import
  import/newline-after-import: 2
  import/imports-first: 2
  import/prefer-default-export: 2
  import/no-dynamic-require: 2
  import/no-extraneous-dependencies: 2
  import/no-mutable-exports: 2
  import/no-commonjs: 2
  import/order: 2
