// list,.js
export const GET_CONTRIBUTION_LIST = "GET_CONTRIBUTION_LIST"
export const GET_CONTRIBUTION_LIST_NEXT = "GET_CONTRIBUTION_LIST_NEXT"
export const ADD_CONTRIBUTION_LIST_ITEM = "ADD_CONTRIBUTION_LIST_ITEM"
export const DELETE_CONTRIBUTION_LIST_ITEM = "DELETE_CONTRIBUTION_LIST_ITEM"
