

export const GET_CONTRIBUTION_LIST = "GET_CONTRIBUTION_LIST"
export const GET_CONTRIBUTION_LIST_NEXT = "GET_CONTRIBUTION_LIST_NEXT"
export const ADD_CONTRIBUTION_LIST_ITEM = "ADD_CONTRIBUTION_LIST_ITEM"
export const DELETE_CONTRIBUTION_LIST_ITEM = "DELETE_CONTRIBUTION_LIST_ITEM"

export const GET_CONTRIBUTION_EDIT = "GET_CONTRIBUTION_EDIT"

export const ADD_CONTRIBUTION_FORM_BODY = "ADD_CONTRIBUTION_FORM_BODY"
export const EDIT_CONTRIBUTION_FORM_BODY = "EDIT_CONTRIBUTION_FORM_BODY"
export const CHANGE_CONTRIBUTION_FORM_CHARACTER = "CHANGE_CONTRIBUTION_FORM_CHARACTER"
export const CHANGE_CONTRIBUTION_FORM_BODY = "CHANGE_CONTRIBUTION_FORM_BODY"
export const CHANGE_CONTRIBUTION_FORM_TITLE = "CHANGE_CONTRIBUTION_FORM_TITLE"
export const CHANGE_CONTRIBUTION_FORM_TAG = "CHANGE_CONTRIBUTION_FORM_TAG"
export const CHANGE_CONTRIBUTION_FORM_HEIGHT = "CHANGE_CONTRIBUTION_FORM_HEIGHT"
export const NEW_CONTRIBUTION_FORM = "NEW_CONTRIBUTION_FORM"


export const GET_CHARACTER_LIST = "GET_CHARACTER_LIST"
export const SET_CHARACTER_LIST = "SET_CHARACTER_LIST"
export const DELETE_CHARACTER_LIST = "DELETE_CHARACTER_LIST"
export const UPLOAD_CHARACTER_LIST = "UPLOAD_CHARACTER_LIST"
