export const INIT_CONTRIBUTION_NEW = "INIT_CONTRIBUTION_NEW"

export const GET_CONTRIBUTION_LIST = "GET_CONTRIBUTION_LIST"
export const GET_CONTRIBUTION_LIST_NEXT = "GET_CONTRIBUTION_LIST_NEXT"
export const ADD_CONTRIBUTION_LIST_ITEM = "ADD_CONTRIBUTION_LIST_ITEM"
export const DELETE_CONTRIBUTION_LIST_ITEM = "DELETE_CONTRIBUTION_LIST_ITEM"

export const GET_CONTRIBUTION_EDIT = "GET_CONTRIBUTION_EDIT"

export const ADD_CONTRIBUTION_FORM_BODY = "ADD_CONTRIBUTION_FORM_BODY"
export const EDIT_CONTRIBUTION_FORM_BODY = "EDIT_CONTRIBUTION_FORM_BODY"
export const EDIT_CONTRIBUTION_FORM_BODY_IMAGE =
  "EDIT_CONTRIBUTION_FORM_BODY_IMAGE"
export const CHANGE_CONTRIBUTION_FORM_CHARACTER =
  "CHANGE_CONTRIBUTION_FORM_CHARACTER"
export const CHANGE_CONTRIBUTION_FORM_BODY = "CHANGE_CONTRIBUTION_FORM_BODY"
export const CHANGE_CONTRIBUTION_FORM_TITLE = "CHANGE_CONTRIBUTION_FORM_TITLE"
export const CHANGE_CONTRIBUTION_FORM_TAG = "CHANGE_CONTRIBUTION_FORM_TAG"
export const CHANGE_CONTRIBUTION_FORM_HEIGHT = "CHANGE_CONTRIBUTION_FORM_HEIGHT"

export const ADD_CONTRIBUTION_TAG = "ADD_CONTRIBUTION_TAG"
export const DELETE_CONTRIBUTION_TAG = "DELETE_CONTRIBUTION_TAG"

export const SET_CONTRIBUTION_FORM_VIEW_STATUS =
  "SET_CONTRIBUTION_FORM_VIEW_STATUS"

export const OPEN_CONTRIBUTION_FORM_HELP = "OPEN_CONTRIBUTION_FORM_HELP"
export const CLOSE_CONTRIBUTION_FORM_HELP = "CLOSE_CONTRIBUTION_FORM_HELP"
export const NEW_CONTRIBUTION_FORM = "NEW_CONTRIBUTION_FORM"
export const SAVE_CONTRIBUTION_FORM = "SAVE_CONTRIBUTION_FORM"
export const UPLOAD_CONTRIBUTION_FORM = "UPLOAD_CONTRIBUTION_FORM"
export const ADD_CONTRIBUTION_FORM_SOUND = "ADD_CONTRIBUTION_FORM_SOUND"
export const GET_CONTRIBUTION_FORM_SOUND_DETAIL =
  "GET_CONTRIBUTION_FORM_SOUND_DETAIL"
export const CANCEL_CONTRIBUTION_FROM_EDIT = "CANCEL_CONTRIBUTION_FROM_EDIT"

export const GET_CONTRIBUTION_SHOW = "GET_CONTRIBUTION_SHOW"
export const DELETE_CONTRIBUTION_SHOW = "DELETE_CONTRIBUTION_SHOW"

export const OPEN_CONTRIBUTION_SHOW_PROBLEM = "OPEN_CONTRIBUTION_SHOW_PROBLEM"
export const CLOSE_CONTRIBUTION_SHOW_PROBLEM = "CLOSE_CONTRIBUTION_SHOW_PROBLEM"
export const SET_CONTRIBUTION_SHOW_PROBLEM_TYPE =
  "SET_CONTRIBUTION_SHOW_PROBLEM_TYPE"
export const ADD_CONTRIBUTION_SHOW_PROBLEM = "ADD_CONTRIBUTION_SHOW_PROBLEM"

export const SET_CONTRIBUTION_TALK_EDIT_BODY = "SET_CONTRIBUTION_TALK_EDIT_BODY"
export const DELETE_CONTRIBUTION_TALK_BODY = "DELETE_CONTRIBUTION_TALK_BODY"
export const SET_CONTRIBUTION_TALK_LIST = "SET_CONTRIBUTION_TALK_LIST"

export const GET_CONTRIBUTION_SEARCH_LIST = "GET_CONTRIBUTION_SEARCH_LIST"
export const PAGING_CONTRIBUTION_SEARCH_LIST = "PAGING_CONTRIBUTION_SEARCH_LIST"
export const SET_CONTRIBUTION_SEARCH_ORDER = "SET_CONTRIBUTION_SEARCH_ORDER"

export const ADD_FOLLOW = "ADD_FOLLOW"
export const DELETE_FOLLOW = "DELETE_FOLLOW"

export const INIT_CHARACTER_LIST = "INIT_CHARACTER_LIST"
export const GET_CHARACTER_LIST = "GET_CHARACTER_LIST"
export const SET_CHARACTER_LIST = "SET_CHARACTER_LIST"
export const SET_CHARACTER_LIST_DEFAULT = "SET_CHARACTER_LIST_DEFAULT"
export const DELETE_CHARACTER_LIST = "DELETE_CHARACTER_LIST"
export const UPLOAD_CHARACTER_LIST = "UPLOAD_CHARACTER_LIST"
export const SET_CHARACTER_VOICE_TYPE = "SET_CHARACTER_VOICE_TYPE"
export const SAVE_CHARACTER_LIST = "SAVE_CHARACTER_LIST"

export const CHANGE_SOUND_SHOW_BODY_SOUND = "CHANGE_SOUND_SHOW_BODY_SOUND"
export const CHANGE_SOUND_SHOW_VOICE_TYPE = "CHANGE_SOUND_SHOW_VOICE_TYPE"
export const CHANGE_SOUND_SHOW_MOVIE_STATUS = "CHANGE_SOUND_SHOW_MOVIE_STATUS"
export const GET_SOUND_LENGTH = "GET_SOUND_LENGTH"
export const SAVE_SOUND_SHOW_BODY_SOUND = "SAVE_SOUND_SHOW_BODY_SOUND"
export const SAVE_SOUND_SHOW_VOICE_TYPE = "SAVE_SOUND_SHOW_VOICE_TYPE"
export const SAVE_SOUND_SHOW = "SAVE_SOUND_SHOW"
export const REFLECT_SOUND_SHOW = "REFLECT_SOUND_SHOW"
export const MAKE_SOUND_SHOW_MOVIE = "MAKE_SOUND_SHOW_MOVIE"
export const UPLOAD_SOUND_YOUTUBE = "UPLOAD_SOUND_YOUTUBE"
export const OFF_SOUND_SHOW_MOVIE_MAKE_LISTENER =
  "OFF_SOUND_SHOW_MOVIE_MAKE_LISTENER"
export const CHECK_SOUND_SHOW_MOVIE = "CHECK_SOUND_SHOW_MOVIE"
export const OPEN_SOUND_SHOW_VOICE_LIST = "OPEN_SOUND_SHOW_VOICE_LIST"
export const CLOSE_SOUND_SHOW_VOICE_LIST = "CLOSE_SOUND_SHOW_VOICE_LIST"
export const SAVE_SOUND_SHOW_VOICE_TYPE_LIST = "SAVE_SOUND_SHOW_VOICE_TYPE_LIST"

export const OPEN_SOUND_MENU_UPLOAD = "OPEN_SOUND_MENU_UPLOAD"
export const CLOSE_SOUND_MENU_UPLOAD = "CLOSE_SOUND_MENU_UPLOAD"
export const OPEN_SOUND_MENU_REMAKE = "OPEN_SOUND_MENU_REMAKE"
export const CLOSE_SOUND_MENU_REMAKE = "CLOSE_SOUND_MENU_REMAKE"
export const MAKING_SOUND_MENU_MOVIE = "MAKING_SOUND_MENU_MOVIE"
export const UPLOADING_SOUND_MENU_MOVIE = "UPLOADING_SOUND_MENU_MOVIE"
export const OPEN_SOUND_MENU_INFORMATION = "OPEN_SOUND_MENU_INFORMATION"
export const CLOSE_SOUND_MENU_INFORMATION = "CLOSE_SOUND_MENU_INFORMATION"

export const INIT_USER_CONTRBUTION_LIST = "INIT_USER_CONTRBUTION_LIST"
export const GET_USER_CONTRBUTION_LIST = "GET_USER_CONTRBUTION_LIST"
export const SET_USER_CONTRBUTION_LIST = "SET_USER_CONTRBUTION_LIST"
export const SET_USER_CONTRBUTION_LIST_SEARCH =
  "SET_USER_CONTRBUTION_LIST_SEARCH"
export const SET_USER_CONTRBUTION_LIST_VIEW_STATUS =
  "SET_USER_CONTRBUTION_LIST_VIEW_STATUS"
export const OPEN_USER_CONTRBUTION_LIST_CONFIRM =
  "OPEN_USER_CONTRBUTION_LIST_CONFIRM"
export const CLOSE_USER_CONTRBUTION_LIST_CONFIRM =
  "CLOSE_USER_CONTRBUTION_LIST_CONFIRM"

export const GET_USER_FOLLOW_LIST = "GET_USER_FOLLOW_LIST"
export const PAGING_USER_FOLLOW_LIST = "PAGING_USER_FOLLOW_LIST"

export const SET_LOGIN_AUTH = "SET_LOGIN_AUTH"
export const LOGOUT_LOGIN_AUTH = "LOGOUT_LOGIN_AUTH"
export const SET_LOGIN_USER = "SET_LOGIN_USER"
export const SET_LOGIN_USER_ALERT = "SET_LOGIN_USER_ALERT"
export const OPEN_LOGIN_TERMS = "OPEN_LOGIN_TERMS"
export const SET_LOGIN_GOOGLE_AUTH = "SET_LOGIN_GOOGLE_AUTH"

export const SHOW_ERROR_MESSAGE = "SHOW_ERROR_MESSAGE"
export const CLOSE_ERROR_MESSAGE = "CLOSE_ERROR_MESSAGE"
export const OPEN_ERROR_BUG_REPORT = "OPEN_ERROR_BUG_REPORT"
export const ADD_ERROR_BUG_REPORT = "ADD_ERROR_BUG_REPORT"
export const CLOSE_ERROR_ALERT_MESSAGE = "CLOSE_ERROR_ALERT_MESSAGE"
export const OPEN_ERROR_ALERT_MESSAGE = "OPEN_ERROR_ALERT_MESSAGE"
export const INIT_ERROR_ALERT_MESSAGE = "INIT_ERROR_ALERT_MESSAGE"

export const SET_USER_MYPAGE_ICON = "SET_USER_MYPAGE_ICON"
export const SET_USER = "SET_USER"
export const UPLOAD_USER_PROFILE = "UPLOAD_USER_PROFILE"
export const CHANGE_USER_NAME = "CHANGE_USER_NAME"
export const SAVE_USER = "SAVE_USER"

export const ADD_PASSWORD = "ADD_PASSWORD"
export const CHECK_PASSWORD = "CHECK_PASSWORD"
export const SAVE_PASSWORD = "SAVE_PASSWORD"

export const INIT_MESSAGE_SHOW = "INIT_MESSAGE_SHOW"
export const OPEN_MESSAGE_SHOW = "OPEN_MESSAGE_SHOW"
export const CLOSE_MESSAGE_SHOW = "CLOSE_MESSAGE_SHOW"

export const ON_LOADING = "ON_LOADING"
export const OFF_LOADING = "OFF_LOADING"

export const INIT_QUESTION = "INIT_QUESTION"
export const ADD_QUESTION = "ADD_QUESTION"

export const GET_JSON = "GET_JSON"
