

export const GET_CONTRIBUTION_LIST = "GET_CONTRIBUTION_LIST"
export const GET_CONTRIBUTION_LIST_NEXT = "GET_CONTRIBUTION_LIST_NEXT"
export const ADD_CONTRIBUTION_LIST_ITEM = "ADD_CONTRIBUTION_LIST_ITEM"
export const DELETE_CONTRIBUTION_LIST_ITEM = "DELETE_CONTRIBUTION_LIST_ITEM"

export const GET_CONTRIBUTION_EDIT = "GET_CONTRIBUTION_EDIT"

export const ADD_CONTRIBUTION_FORM_BODY = "ADD_CONTRIBUTION_FORM_BODY"
export const EDIT_CONTRIBUTION_FORM_BODY = "EDIT_CONTRIBUTION_FORM_BODY"
export const CHANGE_CONTRIBUTION_FORM_CHARACTER = "CHANGE_CONTRIBUTION_FORM_CHARACTER"
export const CHANGE_CONTRIBUTION_FORM_BODY = "CHANGE_CONTRIBUTION_FORM_BODY"
export const CHANGE_CONTRIBUTION_FORM_TITLE = "CHANGE_CONTRIBUTION_FORM_TITLE"
export const CHANGE_CONTRIBUTION_FORM_TAG = "CHANGE_CONTRIBUTION_FORM_TAG"
export const CHANGE_CONTRIBUTION_FORM_HEIGHT = "CHANGE_CONTRIBUTION_FORM_HEIGHT"

export const SET_CONTRIBUTION_FORM_VIEW_STATUS = "SET_CONTRIBUTION_FORM_VIEW_STATUS"

export const NEW_CONTRIBUTION_FORM = "NEW_CONTRIBUTION_FORM"
export const SAVE_CONTRIBUTION_FORM = "SAVE_CONTRIBUTION_FORM"
export const UPLOAD_CONTRIBUTION_FORM = "UPLOAD_CONTRIBUTION_FORM"

export const GET_CONTRIBUTION_SHOW = "GET_CONTRIBUTION_SHOW"
export const DELETE_CONTRIBUTION_SHOW = "DELETE_CONTRIBUTION_SHOW"

export const SET_CONTRIBUTION_TALK_EDIT_BODY = "SET_CONTRIBUTION_TALK_EDIT_BODY"
export const DELETE_CONTRIBUTION_TALK_BODY = "DELETE_CONTRIBUTION_TALK_BODY"
export const SET_CONTRIBUTION_TALK_LIST = "SET_CONTRIBUTION_TALK_LIST"

export const GET_CONTRIBUTION_SEARCH_LIST = "GET_CONTRIBUTION_SEARCH_LIST"
export const PAGING_CONTRIBUTION_SEARCH_LIST = "PAGING_CONTRIBUTION_SEARCH_LIST"

export const ADD_FOLLOW = "ADD_FOLLOW"
export const DELETE_FOLLOW = "DELETE_FOLLOW"

export const GET_CHARACTER_LIST = "GET_CHARACTER_LIST"
export const SET_CHARACTER_LIST = "SET_CHARACTER_LIST"
export const DELETE_CHARACTER_LIST = "DELETE_CHARACTER_LIST"
export const UPLOAD_CHARACTER_LIST = "UPLOAD_CHARACTER_LIST"

export const GET_USER_CONTRBUTION_LIST = "GET_USER_CONTRBUTION_LIST"
export const SET_USER_CONTRBUTION_LIST = "SET_USER_CONTRBUTION_LIST"

export const GET_USER_FOLLOW_LIST = "GET_USER_FOLLOW_LIST"
export const PAGING_USER_FOLLOW_LIST = "PAGING_USER_FOLLOW_LIST"

export const SET_LOGIN_AUTH = "SET_LOGIN_AUTH"
export const LOGOUT_LOGIN_AUTH = "LOGOUT_LOGIN_AUTH"
export const SET_LOGIN_USER = "SET_LOGIN_USER"

export const SHOW_ERROR_MESSAGE = "SHOW_ERROR_MESSAGE"
export const CLOSE_ERROR_MESSAGE = "CLOSE_ERROR_MESSAGE"

export const SET_USER_MYPAGE_ICON = "SET_USER_MYPAGE_ICON"
export const SET_USER = "SET_USER"
export const UPLOAD_USER_PROFILE = "UPLOAD_USER_PROFILE"
export const CHANGE_USER_NAME = "CHANGE_USER_NAME"
export const SAVE_USER = "SAVE_USER"

export const ADD_PASSWORD = "ADD_PASSWORD"
export const CHECK_PASSWORD = "CHECK_PASSWORD"
export const SAVE_PASSWORD = "SAVE_PASSWORD"
